apiVersion: v1
kind: ConfigMap
metadata:
  name: filesync-config
data:
  SERVER_PORT: "8080"
  MINIO_ENDPOINT: "minio.storage.svc.cluster.local:9000"
  MINIO_BUCKET: "filesync"
  MINIO_USE_SSL: "false"
