apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: filesync-ingress
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - filesync.homelab.local
      secretName: filesync-tls
  rules:
    - host: filesync.homelab.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: filesync-api
                port:
                  name: http
