apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml
  - secret-db.yaml
  - secret-minio.yaml
  - secret-redis.yaml
  - ingress.yaml
  - worker-deployment.yaml
  - hpa-api.yaml
  - keda-scaledobject.yaml
  - servicemonitor.yaml
  - podmonitor-worker.yaml
  - prometheus-rules.yaml
