apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - helmrepository.yaml
  - helmrelease-postgres.yaml
  - helmrelease-redis.yaml
  - helmrelease-minio.yaml
  - helmrelease-tailscale.yaml
  - deployment.yaml
  - service.yaml
  - web-deployment.yaml
  - web-service.yaml
  - configmap.yaml
  - sealed-secret-db.yaml
  - sealed-secret-minio.yaml
  - sealed-secret-redis.yaml
  - sealed-secret-tailscale.yaml
  - sealed-secret-ghcr.yaml
  - sealed-secret-ghcr-flux.yaml
  - sealed-secret-postgres-helm.yaml
  - sealed-secret-redis-helm.yaml
  - sealed-secret-minio-helm.yaml
  - image-automation.yaml
  - proxyclass.yaml
  - ingress.yaml
  - worker-deployment.yaml
  - hpa-api.yaml
  - keda-scaledobject.yaml
  - servicemonitor.yaml
  - podmonitor-worker.yaml
  - prometheus-rules.yaml
