---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-auth
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgANM20J4iNoEu//4I2kUgaVNAjZxid2FPTKLR9Cst6SnofRGmyl10dab0pDlU0wudkDy2V4sss9Qk9Q1bauAOso2Z0Xzn4QRDy6+AYzbKBAPplCvXZnjOrbza0XThrkXNf/vL4oiyOiEP7Ray7CBBBUixGBk0TmBiu5/8I/XNBgVQ8mX/Oy4mn8XYepnZ4gr4llqrJr2OXDp4DYBSbdlDmpXGviOAucbMGGGFvO7AUZQu2bG+FjLqGJMbMey/Z02Zn9Ft/9You9gtcFwA/Heq52PUuMumvpX2KxZ1OEo4IPlwKXk//7otl/v57C5+xiKLWIxSF7F5Hr30/K9Hztg9TfGdoP0JVO72Z0gFzvm6KGqCrEg3lho+2hdyJv5+vf0ax2QwotA7dtJrA08czQ5jDxE7qlNJu4drM35XXVX9mwoenXSIp+RAtc72F+z3bXm3r2kEcRS+7f8oyRMv07xh7joI4pStKHZHojnytoG6jEhaHPyewM0PBV0oBJnpnwxAtJJf4zjLsLBiEWIeO94A+LkLGPKsSCvPSMwc5xZsbTVUDKE4J7/3dt2PyF5AZq4jJEgatEezvpbcakJIhPhJhRs+RSLcojsBq8A3Y6PJEkWUm2y0jFHzm3A6erJeMZAuCdGPPXVv+dnyyzTeftk35fsTlYvcgAnUk9HqmI4OZCTzwGcQTcWoTh8WoJ7HxSIk2aIQTOB5HikIwtpdNCiJG1GeDx6L1VqzZ+g2cX1rounaYD0JS+ZeAinKDZfB9BxkvNXVmKQH/DAAnlwFwvmRbVUIf0stUAhJH4EF7jFAElpR0SMbqfaCaLYCnhHNC0uVmnHQXR+6DWCA2GWJ5ws+ZKfdCj6p7Yt4V5miUwhkC10bagXsEkdxqwNcMg0Ixp8M2Sz5dI5+eaicGxqeQPrG+bfHIjn+/x+CmPdIct9fby0jRSdnHyPV5Ist1pe7UxjhtrClrYswzE70MTN6mW2lGVRZjM
  template:
    metadata:
      name: ghcr-auth
      namespace: default
    type: kubernetes.io/dockerconfigjson
