---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filesync-redis-credentials
  namespace: default
spec:
  encryptedData:
    REDIS_PASSWORD: AgBOvRY2nSSDNKoHsCA8EJTu/D6stTXVDAdfHuu6pUVvxDDAN+dmDfxK2xmw5bzFdZGshklnCTGFnk48PYQQHbczdxjXFSF2n3/MKwd3+CNL1ZFhDCe2rZtWeRBzH/YUZ3jewq2Oosu0T6YFkowpk26UrgmdYVSK3WEfwtjF8HbSh8koN3aG9SdpZCpAfox6UfTlFt2A/gLEc0ibHnh/bmvmZ2Mc6YPQzeW0TQX9f0QcixzghavBcVMs6GTxgF/i0PHfxWBP1i8cSaZ1BuSC5WixtLXOgZDt+QuDS3WFp0SBWp8FP73wAFJy2hDXZRcn3PY6F6TQ1c5gza7Tf4QQygt9gYF0S4MqJ95WlbSxTXlyZEhSUePVeZ2pQmfajQTnHkO2Auu78kf8+ySOidcnc9z6lTjPQ3sgn9xJ5qpapyO6LFdWFVJI3PqqugRpiy6C1NdhqbBCt/vgv2HTy1myVJKF2It++Q0hslDbNkxEqeacTYbXWAxRHap3gDvtMV1d4W2ExVfMsTGP5pzLl/2lLazUubznVRE1O60I+e3ZoC63IusdpRK5RjGvtTdpqpKyS/JJSmBtjk9xFUkJ2D5b+vwJz1LxsxlzjMYwEk4+vuEvMR3piMJnPPaLUyBt+9zIdJbE2bezxGmGP0+wrggK9wrI6Lj2VeARwXKNv3xgQTs0WgKctgGFKxUJXQRj8Xn2vYTWPcH0DLQPRHus7DGVo7lQHAG0PFYDBF9aHEKaBJ6uBcs=
    REDIS_URL: AgCeBz0AbuNiNy5yqf0VI26CDskmzHn7O0JRPEKooo68rYmvr1skIQCrBa2ukSyh4Wka8krzkHZzwurP+V8mfuPsxccz4F1ndACoaon2HAjoRXIQlCvma3Tkeva6a/6AKRwC2lqbsFPED6NVih8z0vsIui3YTZvMfsR9fYZ3eLi8FVBntRRRPjzlmG/COWyznndnsNHsmtx5CZTdcmoAZyWDyarnJeWyO9G+q6rCL1TNX38InRrkqa2UABVNGOHwF0Mo4631DhsC/4kb0pCqwIrPPaEwX5IWew5xVt8K1B80j47FfMtVKKGjmBmFcuiAEnocQA9B2oH3zBxGoZzZRzLYIAW6HsERO+uIjtmfrD4v3wbozLGQd4sWKb7CC0Jn1YIvRE3up7Eiks+zlTCFsy9X5CKOppoEdCZBVoz+cau9LShiejowBi54nd7RCStFzorbCkczWZg3sqAlPTDEBk2lcnuAviorK8JpmxIpsTDZCaZTeEHmKB3/QkD7bwgdYpOjUWj2x8OrUtX4V3TN3QKWbxAzxjmW0ySr03fK7a21vkc17VZ0jti7bDirQtoOKmyaNaby60vat7mdRyfxp8QGtrk56/e24aPy8f7r4DLnAOfeEFw20N8E6RJD1Yy0bmBzZf6ZQ0511nJbf4gIbP4wlNJaoPoYYssH21Qb2CJaI2KZVXKVFlvlJ5JxqoWxeKO15fKRHQzOSshGwRSyRofRoflW6mweo5fgO6iUdncdxk4Xl9MmbSXt0tg+QCvPPAzft4ye+nOwn4mLaBz1QYuScjJ0axD/yrZloFZkobeQWQzY3unfpQ==
  template:
    metadata:
      name: filesync-redis-credentials
      namespace: default
    type: Opaque
