---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filesync-redis-credentials
  namespace: default
spec:
  encryptedData:
    REDIS_PASSWORD: AgBx7pBkpZhLR3JPW6N/08ngdJP55OAsVnzPYZaRzwdKbSJJfm72tXhbbWMTttnKirHP2YybcUi0cJf7joZgdvg8Q29FKDbflh+wFa9Sy+17eG9hTsbWEH2+Ejuql2AEB5/zJ1fYCi4l0Lj+AkFNSQVHrRUdAcCy9kWDvT1AMLiIu/+AGkQzQBqlNur3rQrrFI5ZhebYAvngNYiMmIRnsAO5eV6hZClSSNSOm+V/fWFyoq9L+6Dt4R1hCQdaQcxEpCJxLt3fumDMDsF4/TH9BCqUIp5avcupORbHly9J/l0gyN4JdTOU6JvxdR5ZvtumP5QkCtdFzpoja+G0MQNK8dP1JkOEmxDe1p9jrgCgNep572YtXMs74cdijwJ3V4g+oCgrz1idEKVtiPQ9Z0mWJ79UuRKHZ9Vo2Q+lRDGURM5OAUvPxVa752cGiGjIBh4+qjH4YNFG0QHbKPMXzKgE7zq+0EtzJVMidxOcyRxw7DRdRowj08yZj1pNDkjMYeqA3ZE0lPnfb0u/1UaUPGXv8BJvNx6S3vSzk4CdI/MOgQ348qw04qdUHu3gpwHnEVEOeKaWL44zLM2WwME0D8lOsGaZD9htmDmrMuYI+Hz5bOQMnB6NET2/TscRw+uxjH3yrTRb299TEU/7FBj3/sf6pHVnXXGfyVPFiZ/Cti8PiQsM0hKFVNxv0+7xV6gK+2KQwwmUTpsPC0Ih3FvBp7+uDzgDbzYJVfxSq6xyR7wcNhTaSjw=
    REDIS_URL: AgAXvCBbLo734kd7XyaYYGdhRe/DKVBGyOISY3kUGbdB6kNrswmKdA2Phfc7inRDDy0WKwAcZGB7RZjvZkDGdpP7LIY1E5GvhVpuHFIljTiQCj6PIjoR8kjZ7QcTadVW6HRmuBvxIWmjoJQ47LrxcPN9roQgIU7UOnhiROWccy3zvSMi7ImdwholIMrDTIWIn7ix+9q+2bGaX984hwC3LDXSkngKDEci4jhHnnH/6tEQhNtnbE+CM7kkSyvlli7LgcLw4hqFt5KXtic+JSGxDKoukl9R45X4/xv92B82IJjha+xnAK95hJRgZjjZKy0jR/E3D0hJ9c2wvxY6NsddbkvIGKWCHMIHEhL+boo2R79X8/Kga+uioaA0oSjLCP/SH4z6Tjd0Xj8uL8pskDpesLNDGId8vJyQCfrm8CWMz7b7nqWeV0RMwho5kqD8eQ/laW2uTils3I18OzxAiZtoJ9fSbyZbfSN79IA8nMV2XO/7eKpVBx/swCG2atoQLSHNDXF2siuUtG1zFt4sTd7NEgGMdnPeENoviUp4M7I+eGwSJr26fxG8I8o41sKzESJrJodZEpZOBK6uUe4z58VZwcWyEEGloat2AN1MIiRp8KU8TFMtrSnSN8htnwWsDk7He1NBAAm+SNV0TCEzR7QsmwGqUXL98iVArQPgD3o3Z2YH2uvkRhYtdUueGENWWTRdm+gtNWPlPJMnWzNLVpLACClnUMhYRk9PYP0xu42ak2W4fvPOwgYLOrwyWO9Dy0Qfn5ZtEBqIE5DprfvoVxyAA2HmQR4uhPiJPKgBWfD0VR00lGzIpDb+duFToQf6Kw==
  template:
    metadata:
      name: filesync-redis-credentials
      namespace: default
    type: Opaque
