---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: minio-credentials
  namespace: storage
spec:
  encryptedData:
    rootPassword: AgBm/xCgLr/NbUmDnzJWcZCIGnYeRFHG9HQHOMEh1riPyPa6vntcEy+XSRNVfZIchuz0avBCBmmqOZYDKnGvUwM3MueLjTKox9jnY/2RpjQnsQjSmWEymd+hx37ZtEvzK+N/31rXpZxmVmEg8sR/6aUlzH/efctV5Fgio7he+lGQq52RqIuG5jIebEmKfV33UjEbQlJWRRQJrG2JiMk6Y2Ai2zn/14Hl/xUxdXpFntpDdBYhN7lINvXopCCnfi+xBHvzFuo2iCSnGbg/qm6UE+4nK2JMJ4erpvKURyKRhnFxw+mEz1eOWZ5Rscm12Yic1sceukAYuinGoetFPr0V5/oxRyUmPf4IxTNRR0J2W1CA6hTYzqCozhMXHta1BPaM0QgeOP1O+quUwbjODhywwgK9HZH1fFI4hdamyWI+CkkguezLcYP1GO2Vq7HX1B9S7CjTImWvQS4Bki0v8Hbx8vDA1CDIGIw1UBUP70EgruBlBk+BkHu+Dg+Ng5zT9hnDLPOggYG+GNw6JaD9MPdY2k7n/y6/bDVVAkDaMDGN1fvnwVPMGMJqDrDIVgnOnsm/K5M1kerFEAMJsSXNxhcu2eBOvnq81f06rT0g0ywTApVEDmvmVc2kbNc4iL7D6AgnbY3qO9mbngV0HKb7DivxIiqE/mRa2UZzyMC5B5IWX20wf10G0ZL77dXsJ0Q34WquHdcqdvqXIEkJz9I89jhq7rmcFxF+Vhw=
    rootUser: AgCzyBLjuxyL8W5XcT1JqtwZ0YUzwF0Sw9rsRH+DQMq2mQ2C8ehhgS1nx9k+bcsX4Fe1yF52rkxFq9X1Fp/6mQRXlr6M4bF/6xQKUhsxQxEH+obW0hzMd4ZrHDGV3FVAQOPxxe4ke81Qp07zqL6naCU8SpOZILqYJuo/nuSeOkX72zzSDAnM8dxZP2pypRkFlK9jJkWqR68vtkQBv2lV1K73NDnQotuYF0O6v9DjY01eAFRrISs0Z3DU2kP0LQ7C47J9Invzki9n8AcOOxxnvZkfqCLNzfifoULVu5JT2RLIhWUMywB/RD8IcQNfjtw2MPK7G3Ke/wMFkR5ez7M5N/zdKau8OhyWDm3yj/PiXOCoGduVX5VRyJneyG6utnp8TBhxFlIHMjV1pWpG0k5B6la77hnUD+QC28/9jHDTO5BkyapJUCZQEsfYcEmzf7I4AhSCp5Z6xfr0lfHwwDnbrtaPFvZDVG9Byp/grxciUFUuQHmMJecyvuV9lPsXsFU2Fu7pIGXmuIVnCZHJLsK9TpL8DsSkP6CxRY7UoyAydA+/Rck4l6XgIYm2HRjWn3GTL8GXtQbJEnGvHvIy1CSKypnYDcWgGkVn0GVKwhK600wJeZ676GGphIvFCC/Xfr+GUJLrodCHYCTTcoOox3rxMWja1mMpTktxSENncTi0TdrV8Okj/7fzXdVvkBZvMYBMLEbKQrj6EOrf2SzD
  template:
    metadata:
      name: minio-credentials
      namespace: storage
