---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-credentials
  namespace: database
spec:
  encryptedData:
    password: AgA0Nhw6T6gDmKojUQOJOpJT5qduOW2DOQaoFjFxyjd4X65/2NkemrG8xYYOINWHKQMyIq95XJ/yeECfzPQPuBxQHkFbzCUB0oBeNZqQASKYo9z9m4ZueBm8VA7JJmzXKrpMHjBt2ntkhpv4ayc1vA/wb0ZHdQ0oABFMqdoAiFLrmgk5Lwujzo1yFAEN5lPilZJcNeI0rEpX/Eud/A+PPqxaGyDQpsuvKzEcym1bME3JI28O4/NKTGeRFjS5uZprwggaVOrOXp5UlIiPTLrWx/ngCxQCj2R/pF25FkrGhrVMYo9Vc0D/dIKMsuBF8s0eWAkv4Yidp5QyDU2ANpnnJdD/kWtX/YZDomG1KDTBi1sbHJA/6j0NLN83F+GINKNlu43zMWU2RX4LMHkoyfZLZFos8reg6ekHNrbdJEH7RAlKI/BbAYLEHoQT8ST4IIAZsIjj7P+/sMflhkxkKYpvfcbUT2lxJOpZOxHk86F1D8xQBZjzhqAqhFloMfwmUloXycEU3BUq7edCoruKEZhTcfuTMkCQ8tSJnOI1v7gw6EUDs9uIAbLWKEMoYAkD0G6v8VQYMgmr4RKZvTDsjbKJ/wq39tNoPcdblexz9tF8qQsWTYhyJ8Wawgkirw0i7osiNhRvkPt8+H3KoJWAPKq7/hU6o5o+bCqcQUHfBcaucM16/DP3Bd4genWWB1W/rtHBsojLoSr9SxlmDmkhdf4F8nvv2Z3bw+O6+9MMf6mnPgx08V0=
    postgres-password: AgCJUEtzDFKQkVGYIDXOXCyUz7v4PAR1yUp1mpyZLWPfofUd2X6DMLPWlONiE6CDmghFcvvnnTuuLZlPOf5r3vSyW6Gr0r8GVVTP29su7l4pf1wg8iUw0S/CCDGNagB5KHTJkyfftaXmftDzVbG16wXGyRz6nL349cbQz0elZ5o62RWeOsXrRADC5GpOj9ofBSmr7iUmUP5KTw8bf0AASy5TV5LV49Y+VS1+qkCCex9Mms3PCh7qcGp13Rx/0K/sHI4pD+Apm5bbpkupRP6CltQ2tludJbWDla2qg01E8gSCJzQ4BfFhTsBBbbNPKVJjqvVecFc/NE8Dtgq3Pslh9Wl4djQtXw1iZOp8GXsuwDnmts9oeKYkoC288g065kWK40lPvvzRptvyHCaSYQzA5l4qQJYhcE7dLMc67zCGvD5QopLrgsMEQQg5bMRtS8/XYDIGl5VMkZmV+NqMvc8hf8ws7+Sn14ylwgVMoxtN1zHQp2abaD4dwFNUYIOscAQyEWzaodDOyzmFE8D/venAME9g0/+Gy1wH2/MBTijb5iVQgZZXlzSEEbD43QIehEr7/xDLcgRse3A81q4TKZAVdh07vO/g/NBFY/igYOmUsSSosvfPKmbSyN5CqJXKsknQv8evGaZD810G9j/1ot7X4fXaDhmOxrM2NsHwZNwYYKVBhR4NYjjLk2t0J9wAOeMjc8Su6SQn+PlYspZNi4QEkdXu5IkRzQPVIh8dFe5qbhoI2uc=
  template:
    metadata:
      name: postgres-credentials
      namespace: database
