---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filesync-db-credentials
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgBb1rlO3cYbzcnQKuqOF4IFi9WH+cxhrmQxNgpZCMI3UVMilD2qAjYznU7+VokVyjL4jCQncMzYYm6U3gQxXAPdLiUuriR34+Ywsp9uiyd4WSLHJG+NxhkwImSiSG12twRTXNumjdvtZjQY7ewtIu0JO9VWJl5c04Y08W5HYyvHIHz05hFjn5ZLjkk0q6z824RYIzKFcCwQpIpzqh7xbPDqi2TR7knFR01tz7nG+sYQcKMyzcyOznGxD5/xxMTqrdhZbGANuU/M8Ohv9IogMWoc4oppuxakNhx5ZnK5ubc7hR8IcWLoUA5xC5rokoVXwNbfUYqwjAIbUPn++qDYnrQQBl3ToIQUSbZfh6jNwsx+AXwnGmqwf1Yb3rGSY11GXuHogd+fxwSRAQ9qqLhUIJqYIGH1KX1gN/N5lGF9dmxFGoN8sESjc4Yz+9i4HHUuJourtiiSYa2F9+utf3WgyUHg8Pj+LWHAtQq8uQG9v/LwaN8q/FoyhEfhrxEinCXrBfXvYlSPWCAMUmN8KVJy7ulBrz91PdD5l+jGYEdkJeBRY27dwVr+Tnpg5f/s5XVVM3g0iKqrF0IYRylgd0NxQ0AeFGLhTEZddeldFUvaXFWa33Er6HN8VgXqEjJGYI0ueP1Ny/2B69nSdFO665HCD/V/Qj6jK9OL3K3MdquQg+Fh1UUXJkI9zVyg3v9I3iVbjufoJ/eufiHNhoDIPgEGVZkpLnjo4qr24F4JjW+q5CqzKijYqgwweAtkYLz7aiccAUtSdHt2HeLxXyRbzcO5TzZFdBONX/nWBF+5K1apR/aQ7XBon0M/wnz/kzXWZgK4clf4ilKihHCp812CN578yVB6cDjNkY0ORPbKrfAyIeChMhdh
  template:
    metadata:
      name: filesync-db-credentials
      namespace: default
    type: Opaque
