---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filesync-minio-credentials
  namespace: default
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCF4laqkWJQL7gXxlZ95SJ08TtoYZ1e1Bm4u+NEVDCdMIxc84jEtr/2fOuDQXf3L71t9zILgAsyB4yM6KVgmbGCPnYWe7XhwZpFeBne6p1/2v2eBbU64865PQOS7uvJM63MyMdWA4q7TsGNUgYOOfmNaSLoX6iNrUyzE+TmOJoxVQJdNl41wcqsd+P/Ht4NVOOZyp0EuV3v+kxOdtLcM8hzzKmeF9lT646WIng4PQkrxd/7S9YyrPwmB7KQ4UPf6budzeQECrRzTML0gBnjFmpMbbwBaoaRstOTY2dZG9sJWshC3LT6gFG1nXuXtdwpVUhuVtQu8eAtoqyDCjyq81ydVqNMAHT4L+s6r0F0Nn5/23yMn8tU7/rzHxBYFCOCdGPPyZ8Z5IzyFDr+/Ib5FX//kCJi8eXmPs+iphC4GBPcDsC1itdMbuZWVDrlciXJNZgxSEm7T/DacDM0bJI+mBQ0klnoZp9Le+3MEF5zdghZ2PVjBkcbbVbj9lUefD95T7zDtsprXZJaqcPT+3IYLC+aLG79VwxCIp1nlRIhIKrmiahVYLKSlTkwdCBrdVNncWiE69n27JCXQt+xrBg3t3P0GzA8lSKir2UY4HDueXpW/a4erNCH/EmG2vFxEZHSUIPTW48cfDmdb+eRhp4BH+lWXNKAi5PBJ+dgr7gvLyEoCpG5Mrk40mgCF4u0lode3cT4ta+9LzTiYKwJ
    MINIO_SECRET_KEY: AgAibhqWwF4lV1qGsILub9/D/xuD0+tvBHaYtmFYN63H6zsj52tMPEAmaSmfzN0PFiiM0SjahXPoBfabJlqU9Aqp/UNNdMAHKPr+gsJrZoXgKsC1LfDKjic3ihtFv+4Z9uS5uFcPocujCNuAf2n90+uTQQrkPN0A4KZjBX1xQPqwXPFTNckYn/twF7jt2Jaw3HuWdudg0CIRTuoSpueZfKtM6CL7kp8mjs74uMlp+VbtAeTHilAwQnhjFflWsb8qOwBR3b/uAf6YjbuxpLDM11xnVHKDXgfwdmzAh7fd3EDAWM3LfCs5GjecXzZ31ow+ZqR2X9JIy+P6nqmFUzfxt7aKA7KVg+B5pvlfeCw29OcbowSlvJHsrEDt/HwxjJWjSJ7IHuEMTAwyMqlRRWcGvb0SQeAuGIK2vq43hhiyuJQIXyRIHtnUdd6wD8xpgxkajVUzuRDOoYoCTO1uksiG5zD2SVIGAKMgi5VuHl1H4c8HX9H6aTojGTP4cap2H9oWV2Y1HxPP6AF6p2y3V513XqY4d+xNEPmh0kCYuxj6w7qgBW6mZRoMAPuXxd2RPgS0FNYwtu3Z4d14SRZlKSGW4Ny6hIFgGs5GBEWoy8YE3fHtRelOuAsAwgFd7/PLbOMiP8qxu/vU3aXjHC363Adm1zKp8zkfCMunB/xVyLykRmfmIPDR2l5KOQfe1jKlNrZ7h8yLu45LKwvSI0suTb8gyR6sEMOIEOA=
  template:
    metadata:
      name: filesync-minio-credentials
      namespace: default
    type: Opaque
