---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: redis-credentials
  namespace: cache
spec:
  encryptedData:
    redis-password: AgCDF+QTprJ7n690A2NMrqqi3+LyWLbCO268OtNbQDOpPGXHJ6RVWoRtgJMFwFa9ZtZzz00ywHgtAM8wJMeLThvzXW2i1KIeCH4GkSwKNOa53LNNB+cr6vtIto0iI30thCbp/30V3+hGxTb6oj12gQIJaEc1CTL63U8M+S8VV1zGx/BJD6nN24EsXF6G2PtlEo9xHRNgdj/t7Zx9K7TGQgrVLaQPsv8FZT8Ox1CBiLhuTcfa8KyPVyQnb+KFinEJwGh2aZZzrMGOPpOXzN4sifGhz5xceIVZvXi6YLTe8IfOtctlEfgeN5UTX05F9sS/NzWBMK/0QVlHaDzZPCVgiplNWPSBWCwZEXkrTlZwoii2cS3cmzDLw1hASbDSJ7SE09F3BTCdBem/+8HoRlnKtBMG/Dd/BojmEmj62G0PDYiP8qobvlVnTB0TI8i+35XKB5O8eMMDqNN5KHd4t+i4DfX2bU098VFNLHy3CQZesOCrPIwKo1SyMMu9AK7vEE9dEiysFbvEgNF3VC/vLfhGQZq1JjuS0bVy8lHs3Rq9VsF9PgiVkD/CDvoUMKnri4StV4gW7jVjrjt0jNDLJ7FlNzG5+VixiNFG1EthYvQ2sdfIEI1Nwlht8q34dhStMofzeLLzWqxXUBQivhN3sKrjHKbpB75uqMLGYc0V1lziarItdE9ZntcPJ+5n+RlrkXmxHR2Oudz2OctO1iBjxQDPRDFnnAdEtm9XWEoUlfLHdsEcRIA=
  template:
    metadata:
      name: redis-credentials
      namespace: cache
