---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-auth
  namespace: flux-system
spec:
  encryptedData:
    .dockerconfigjson: AgClU0Q13BKOnaTG+HzdzZslIQsAECjnZZQFth6oZz81YZRri9Fi6xzF0aUt6/mm7EJNWI+VvOTrhZILmDjLAKVGH0w/ZT8iFq+xuJ7+4nLGwgFltMPnQ8h39Zb4h7NiCRjaGMlDOFEBpDC3QgizaSZqliLHV2y/0nlh1xqH9LV9/J5aZTv369kbJiCTICJO7dFf19KDmxYgfDPqYJFR498FZj2hqmlMR2ugK4ojvMq+dfXUe0q3ZLc239Y8yq2zZSRvOt/S4JQ38fpNelmuSA6qQaxEYglY7vxKRmII80mXBWk+p9aq1IckY29g0usjQjRoA7psRE+4apHYLXNNI5Ji5caVtJD5gVKhfwdG8LwhW3VfHoW5yJKNKUbno95UktyWFkBLK0v0rp1KSlmDaNRI2JKJGEpXITUiA5uvuF2RSIGOSYe0iUvjOk3p+H5uSkmkh/40LuBpfQzTU0oL8erfdJG+2chVQ42rm6/ZQwGyqMT5P0VtNRZBWtAoJltORvtG1eL2AiMSMLwPoduM3rtxgLFTCZR+6xofQSQ0a0wVuSlpsZCT4Tfe7xjJ7X9nEwUJ/M3bcPnVv4rszp4G9NZIbRepVhZ78Gec7M27Qrdcntap+miE04DiCG2tzPKXcJ6o5eAl68JMKdQPtgszJ0mlF0KYGbTKgXZZ0sEbw2LZ6YWr1fheIHX5jkM5KvTd1uh25wa4m6OVcAm7FD5MmYQ07Ghda8YVyRgkXPi5dN73cdSsehb0byt3/0VKf9lFIS6vJNWGyXeoNGzotS43ATwlVnChddyG1M5moN9HpEkiwW8UfcMF6p1+DfCGGE+u7LaC/C0rONnrPQm/UzJy/aSMQzChDztcofkjQMmv5etxivBwLz04K8rJRiMkE0RGkMRfrlWW+9cZYhK3RNHuxM/YviTmIfU7CFuNHVfCszWoOmBtdXqmBKpYRw0XgpZCAg2tddppsQ5eLme17Jovf4eKdMey
  template:
    metadata:
      name: ghcr-auth
      namespace: flux-system
    type: kubernetes.io/dockerconfigjson
