---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: filesync-db-credentials
  namespace: default
spec:
  encryptedData:
    DATABASE_URL: AgCejyipfmI6IytJSLi6wVugMvmaBiZO5n1is4Ma8UdxfIaGqXsMwWzbcI7SBldJ7zaHMSN1GAfOY23NhGxjBQUA51b2LEq1Ion+ix5Kb8Ip/2J6bEG5YmY4feBcKxdXyjp+2tsfysJyH0LL7Q8a8MYjv4Qa4c3ksFH3wDSs++2hwOaoxfLOxvsfTIjj3dHm2/2wpluD4yVOYN3zQ94Z803ZIhzLcOle82gFKmFke72+QMBpfIWDPs5cQwhI1boCCMNDUUzEcxonUNDNuNFVr5KlhtulNyJFd3lxZvBoibXb3XWuHAQN/4MKOkWutyRbTdDHNWXUncJCP6zOVlySgqjEWVF+XzB7EK1ldO8iIgIXLspnaCXh1Bb1PDbWjMb4uKv1KOnO/aG13ss5xweRp5gUeCC8vtrUToIa4IM+eUAUqkkjWODwwtoxuDhwsuXL8ERsbaJa0uQMXNXCyGnYl+iheLGAeEAGkdzFlfPAuIu8rIyvKAIDY5CG5z/LUjiV+qkl1BB764Pvx4yq7TAmyrBTUH4tJAv91JUsHpIVa9KJevfKPRDSIzmGeMEB7j5TTNfBPnI7MAea8GPMFYnzj7HfI/gTgxNrq7euxXCkLLUmso4ic6vPA51N37HaB2AZNa582+Ws2gJ0zbP3PJFHHRPtn68EdTdK1g2WyYOy9jyC2wmN4/o8mB7/cLWmdb1K1CoXmDQIUDf5WxyobM0fCxPUNrFOEQjkvHL5+MSWprdNQYSbZy/FAdi0f/qkTw9cYifORCHvuTxe4AYYNzUILIdfbRhf1w+StJi7bbTJYT9VfJHG+I2+OzQqgFOEk8czBFFNY2fPq/dNeWGnlfvW8gGsppaYIR17I5v1U/2miN9Aq9yxiNrNfdCS4zl3
  template:
    metadata:
      name: filesync-db-credentials
      namespace: default
    type: Opaque
