apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: filesync-api
  namespace: default
  labels:
    app: filesync
    component: api
spec:
  selector:
    matchLabels:
      app: filesync
      component: api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
