apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
images:
  - name: the-ranch
    newName: ghcr.io/opalwight/the-ranch/api
    newTag: latest
  - name: the-ranch-worker
    newName: ghcr.io/opalwight/the-ranch/worker
    newTag: latest
  - name: the-ranch-web
    newName: ghcr.io/opalwight/the-ranch/web
    newTag: latest
